#version 450

layout(local_size_x = 1, local_size_y = 1) in;

// downsampled output
layout(binding = 0) uniform sampler2D source;
layout(binding = 1, rgba16f) uniform image2D target;

void main() {
    vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(imageSize(target));

    vec4 sampled = texture(source, uv);
    //sampled.rgb /= 2.0;

    imageStore(target, ivec2(gl_GlobalInvocationID.xy), sampled);
}